ARCH_LINUX_ZIP_URL = "https://github.com/yuk7/ArchWSL/releases/download/24.3.11.0/Arch.zip"
ARCH_LINUX_ZIP_FILENAME = "arch.zip"
ARCH_LINUX_DIR = "arch"
DEFAULT_SHELL = "bash"
MINICONDA_URL = "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
MINICONDA_FILE = "miniconda.sh"